/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class SWMFIono extends Model {
  private long swigCPtr;

  protected SWMFIono(long cPtr, boolean cMemoryOwn) {
    super(CCMCJNI.SWMFIono_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SWMFIono obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_SWMFIono(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SWMFIono() {
    this(CCMCJNI.new_SWMFIono(), true);
  }

  public int open(String filename) {
    return CCMCJNI.SWMFIono_open(swigCPtr, this, filename);
  }

  public Interpolator createNewInterpolator() {
    long cPtr = CCMCJNI.SWMFIono_createNewInterpolator(swigCPtr, this);
    return (cPtr == 0) ? null : new Interpolator(cPtr, false);
  }

  public vector_string getLoadedVariables() {
    return new vector_string(CCMCJNI.SWMFIono_getLoadedVariables(swigCPtr, this), true);
  }

}
