/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class Time {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Time(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Time obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_Time(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Time(String epochString) {
    this(CCMCJNI.new_Time__SWIG_0(epochString), true);
  }

  public Time(double epoch) {
    this(CCMCJNI.new_Time__SWIG_1(epoch), true);
  }

  public Time() {
    this(CCMCJNI.new_Time__SWIG_2(), true);
  }

  public short getDay() {
    return CCMCJNI.Time_getDay(swigCPtr, this);
  }

  public void setDay(short day) {
    CCMCJNI.Time_setDay(swigCPtr, this, day);
  }

  public void setEpoch(double epoch) {
    CCMCJNI.Time_setEpoch(swigCPtr, this, epoch);
  }

  public short getHour() {
    return CCMCJNI.Time_getHour(swigCPtr, this);
  }

  public void setHour(short hour) {
    CCMCJNI.Time_setHour(swigCPtr, this, hour);
  }

  public short getMilliseconds() {
    return CCMCJNI.Time_getMilliseconds(swigCPtr, this);
  }

  public void setMilliseconds(short milliseconds) {
    CCMCJNI.Time_setMilliseconds(swigCPtr, this, milliseconds);
  }

  public short getMinute() {
    return CCMCJNI.Time_getMinute(swigCPtr, this);
  }

  public void setMinute(short minute) {
    CCMCJNI.Time_setMinute(swigCPtr, this, minute);
  }

  public short getMonth() {
    return CCMCJNI.Time_getMonth(swigCPtr, this);
  }

  public void setMonth(short month) {
    CCMCJNI.Time_setMonth(swigCPtr, this, month);
  }

  public short getSeconds() {
    return CCMCJNI.Time_getSeconds(swigCPtr, this);
  }

  public void setSeconds(double seconds) {
    CCMCJNI.Time_setSeconds(swigCPtr, this, seconds);
  }

  public short getYear() {
    return CCMCJNI.Time_getYear(swigCPtr, this);
  }

  public void setYear(short year) {
    CCMCJNI.Time_setYear(swigCPtr, this, year);
  }

  public String toString() {
    return CCMCJNI.Time_toString(swigCPtr, this);
  }

  public double getEpoch() {
    return CCMCJNI.Time_getEpoch(swigCPtr, this);
  }

}
