/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class ENLIL extends Model {
  private long swigCPtr;

  protected ENLIL(long cPtr, boolean cMemoryOwn) {
    super(CCMCJNI.ENLIL_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENLIL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_ENLIL(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ENLIL() {
    this(CCMCJNI.new_ENLIL(), true);
  }

  public int open(String filename) {
    return CCMCJNI.ENLIL_open(swigCPtr, this, filename);
  }

  public Interpolator createNewInterpolator() {
    long cPtr = CCMCJNI.ENLIL_createNewInterpolator(swigCPtr, this);
    return (cPtr == 0) ? null : new Interpolator(cPtr, false);
  }

  public boolean getChangeSignFlag(String variable) {
    return CCMCJNI.ENLIL_getChangeSignFlag(swigCPtr, this, variable);
  }

  public boolean getChangeSignFlagByID(int variable_id) {
    return CCMCJNI.ENLIL_getChangeSignFlagByID(swigCPtr, this, variable_id);
  }

  public vector_string getLoadedVariables() {
    return new vector_string(CCMCJNI.ENLIL_getLoadedVariables(swigCPtr, this), true);
  }

}
