/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class OpenGGCM extends Model {
  private long swigCPtr;

  protected OpenGGCM(long cPtr, boolean cMemoryOwn) {
    super(CCMCJNI.OpenGGCM_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpenGGCM obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_OpenGGCM(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OpenGGCM() {
    this(CCMCJNI.new_OpenGGCM(), true);
  }

  public int open(String filename) {
    return CCMCJNI.OpenGGCM_open(swigCPtr, this, filename);
  }

  public Interpolator createNewInterpolator() {
    long cPtr = CCMCJNI.OpenGGCM_createNewInterpolator(swigCPtr, this);
    return (cPtr == 0) ? null : new Interpolator(cPtr, false);
  }

  public vector_float getXGrid(String variable) {
    long cPtr = CCMCJNI.OpenGGCM_getXGrid__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getXGrid(int variable) {
    long cPtr = CCMCJNI.OpenGGCM_getXGrid__SWIG_1(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getYGrid(String variable) {
    long cPtr = CCMCJNI.OpenGGCM_getYGrid__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getYGrid(int variable) {
    long cPtr = CCMCJNI.OpenGGCM_getYGrid__SWIG_1(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getZGrid(String variable) {
    long cPtr = CCMCJNI.OpenGGCM_getZGrid__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getZGrid(int variable) {
    long cPtr = CCMCJNI.OpenGGCM_getZGrid__SWIG_1(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public String getXGridName(String variable) {
    return CCMCJNI.OpenGGCM_getXGridName__SWIG_0(swigCPtr, this, variable);
  }

  public String getXGridName(int variable_id) {
    return CCMCJNI.OpenGGCM_getXGridName__SWIG_1(swigCPtr, this, variable_id);
  }

  public String getYGridName(String variable) {
    return CCMCJNI.OpenGGCM_getYGridName__SWIG_0(swigCPtr, this, variable);
  }

  public String getYGridName(int variable_id) {
    return CCMCJNI.OpenGGCM_getYGridName__SWIG_1(swigCPtr, this, variable_id);
  }

  public String getZGridName(String variable) {
    return CCMCJNI.OpenGGCM_getZGridName__SWIG_0(swigCPtr, this, variable);
  }

  public String getZGridName(int variable_id) {
    return CCMCJNI.OpenGGCM_getZGridName__SWIG_1(swigCPtr, this, variable_id);
  }

  public vector_string getLoadedVariables() {
    return new vector_string(CCMCJNI.OpenGGCM_getLoadedVariables(swigCPtr, this), true);
  }

}
