/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class CCMC {
  public static double parseEPOCH3(String epString) {
    return CCMCJNI.parseEPOCH3(epString);
  }

  public static void encodeEPOCH3(double epoch, String epString) {
    CCMCJNI.encodeEPOCH3(epoch, epString);
  }

}
