/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class HDF5FileReader extends FileReader {
  private long swigCPtr;

  public HDF5FileReader(long cPtr, boolean cMemoryOwn) {
    super(CCMCJNI.HDF5FileReader_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(HDF5FileReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_HDF5FileReader(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HDF5FileReader() {
    this(CCMCJNI.new_HDF5FileReader(), true);
  }

  public vector_float getVariable(String variable) {
    long cPtr = CCMCJNI.HDF5FileReader_getVariable__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getVariable(int variable) {
    long cPtr = CCMCJNI.HDF5FileReader_getVariable__SWIG_1(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getVariable(String variable, int startIndex, int count) {
    long cPtr = CCMCJNI.HDF5FileReader_getVariable__SWIG_2(swigCPtr, this, variable, startIndex, count);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getVariable(int variable, int startIndex, int count) {
    long cPtr = CCMCJNI.HDF5FileReader_getVariable__SWIG_3(swigCPtr, this, variable, startIndex, count);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public float getVariableAtIndex(String variable, int index) {
    return CCMCJNI.HDF5FileReader_getVariableAtIndex__SWIG_0(swigCPtr, this, variable, index);
  }

  public float getVariableAtIndex(int variable_id, int index) {
    return CCMCJNI.HDF5FileReader_getVariableAtIndex__SWIG_1(swigCPtr, this, variable_id, index);
  }

  public vector_int getVariableInt(String variable) {
    long cPtr = CCMCJNI.HDF5FileReader_getVariableInt(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_int(cPtr, false);
  }

  public int getVariableIntAtIndex(String variable, int index) {
    return CCMCJNI.HDF5FileReader_getVariableIntAtIndex(swigCPtr, this, variable, index);
  }

  public int getNumberOfGlobalAttributes() {
    return CCMCJNI.HDF5FileReader_getNumberOfGlobalAttributes(swigCPtr, this);
  }

  public int getNumberOfVariables() {
    return CCMCJNI.HDF5FileReader_getNumberOfVariables(swigCPtr, this);
  }

  public int getNumberOfVariableAttributes() {
    return CCMCJNI.HDF5FileReader_getNumberOfVariableAttributes(swigCPtr, this);
  }

  public int getNumberOfRecords(String variable) {
    return CCMCJNI.HDF5FileReader_getNumberOfRecords__SWIG_0(swigCPtr, this, variable);
  }

  public int getNumberOfRecords(int variable_id) {
    return CCMCJNI.HDF5FileReader_getNumberOfRecords__SWIG_1(swigCPtr, this, variable_id);
  }

  public int getVariableID(String variable) {
    return CCMCJNI.HDF5FileReader_getVariableID(swigCPtr, this, variable);
  }

  public String getVariableName(int variable_id) {
    return CCMCJNI.HDF5FileReader_getVariableName(swigCPtr, this, variable_id);
  }

  public Attribute getGlobalAttribute(int i) {
    return new Attribute(CCMCJNI.HDF5FileReader_getGlobalAttribute__SWIG_0(swigCPtr, this, i), true);
  }

  public String getGlobalAttributeName(int attribute_id) {
    return CCMCJNI.HDF5FileReader_getGlobalAttributeName(swigCPtr, this, attribute_id);
  }

  public String getVariableAttributeName(int attribute_id) {
    return CCMCJNI.HDF5FileReader_getVariableAttributeName(swigCPtr, this, attribute_id);
  }

  public Attribute getGlobalAttribute(String attribute) {
    return new Attribute(CCMCJNI.HDF5FileReader_getGlobalAttribute__SWIG_1(swigCPtr, this, attribute), true);
  }

  public Attribute getVariableAttribute(String variable, String attribute) {
    return new Attribute(CCMCJNI.HDF5FileReader_getVariableAttribute(swigCPtr, this, variable, attribute), true);
  }

  public vector_string getVariableAttributeNames() {
    return new vector_string(CCMCJNI.HDF5FileReader_getVariableAttributeNames(swigCPtr, this), true);
  }

  public boolean doesAttributeExist(String attribute) {
    return CCMCJNI.HDF5FileReader_doesAttributeExist(swigCPtr, this, attribute);
  }

  public boolean doesVariableExist(String variable) {
    return CCMCJNI.HDF5FileReader_doesVariableExist(swigCPtr, this, variable);
  }

  public String getCurrentFilename() {
    return CCMCJNI.HDF5FileReader_getCurrentFilename(swigCPtr, this);
  }

}
