/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class CDFFileReader extends FileReader {
  private long swigCPtr;

  protected CDFFileReader(long cPtr, boolean cMemoryOwn) {
    super(CCMCJNI.CDFFileReader_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CDFFileReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_CDFFileReader(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CDFFileReader() {
    this(CCMCJNI.new_CDFFileReader(), true);
  }

  public vector_float getVariable(String variable) {
    long cPtr = CCMCJNI.CDFFileReader_getVariable__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getVariable(int variableID) {
    long cPtr = CCMCJNI.CDFFileReader_getVariable__SWIG_1(swigCPtr, this, variableID);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getVariable(String variable, int startIndex, int count) {
    long cPtr = CCMCJNI.CDFFileReader_getVariable__SWIG_2(swigCPtr, this, variable, startIndex, count);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getVariable(int variableID, int startIndex, int count) {
    long cPtr = CCMCJNI.CDFFileReader_getVariable__SWIG_3(swigCPtr, this, variableID, startIndex, count);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public float getVariableAtIndex(String variable, int index) {
    return CCMCJNI.CDFFileReader_getVariableAtIndex__SWIG_0(swigCPtr, this, variable, index);
  }

  public float getVariableAtIndex(int variable_id, int index) {
    return CCMCJNI.CDFFileReader_getVariableAtIndex__SWIG_1(swigCPtr, this, variable_id, index);
  }

  public vector_int getVariableInt(String variable) {
    long cPtr = CCMCJNI.CDFFileReader_getVariableInt(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_int(cPtr, false);
  }

  public int getVariableIntAtIndex(String variable, int index) {
    return CCMCJNI.CDFFileReader_getVariableIntAtIndex(swigCPtr, this, variable, index);
  }

  public int getNumberOfGlobalAttributes() {
    return CCMCJNI.CDFFileReader_getNumberOfGlobalAttributes(swigCPtr, this);
  }

  public int getNumberOfVariables() {
    return CCMCJNI.CDFFileReader_getNumberOfVariables(swigCPtr, this);
  }

  public int getNumberOfVariableAttributes() {
    return CCMCJNI.CDFFileReader_getNumberOfVariableAttributes(swigCPtr, this);
  }

  public int getNumberOfRecords(String variable) {
    return CCMCJNI.CDFFileReader_getNumberOfRecords__SWIG_0(swigCPtr, this, variable);
  }

  public int getNumberOfRecords(int variable_id) {
    return CCMCJNI.CDFFileReader_getNumberOfRecords__SWIG_1(swigCPtr, this, variable_id);
  }

  public int getVariableID(String variable) {
    return CCMCJNI.CDFFileReader_getVariableID(swigCPtr, this, variable);
  }

  public String getVariableName(int variable_id) {
    return CCMCJNI.CDFFileReader_getVariableName(swigCPtr, this, variable_id);
  }

  public Attribute getGlobalAttribute(int i) {
    return new Attribute(CCMCJNI.CDFFileReader_getGlobalAttribute__SWIG_0(swigCPtr, this, i), true);
  }

  public String getGlobalAttributeName(int attribute_id) {
    return CCMCJNI.CDFFileReader_getGlobalAttributeName(swigCPtr, this, attribute_id);
  }

  public String getVariableAttributeName(int attribute_id) {
    return CCMCJNI.CDFFileReader_getVariableAttributeName(swigCPtr, this, attribute_id);
  }

  public Attribute getGlobalAttribute(String attribute) {
    return new Attribute(CCMCJNI.CDFFileReader_getGlobalAttribute__SWIG_1(swigCPtr, this, attribute), true);
  }

  public int getGlobalAttributeID(String attribute) {
    return CCMCJNI.CDFFileReader_getGlobalAttributeID(swigCPtr, this, attribute);
  }

  public Attribute getVariableAttribute(String variable, String attribute) {
    return new Attribute(CCMCJNI.CDFFileReader_getVariableAttribute(swigCPtr, this, variable, attribute), true);
  }

  public vector_string getVariableAttributeNames() {
    return new vector_string(CCMCJNI.CDFFileReader_getVariableAttributeNames(swigCPtr, this), true);
  }

  public boolean doesAttributeExist(String attribute) {
    return CCMCJNI.CDFFileReader_doesAttributeExist__SWIG_0(swigCPtr, this, attribute);
  }

  public boolean doesVariableExist(String variable) {
    return CCMCJNI.CDFFileReader_doesVariableExist__SWIG_0(swigCPtr, this, variable);
  }

  public boolean doesAttributeExist(int attribute) {
    return CCMCJNI.CDFFileReader_doesAttributeExist__SWIG_1(swigCPtr, this, attribute);
  }

  public boolean doesVariableExist(int variable) {
    return CCMCJNI.CDFFileReader_doesVariableExist__SWIG_1(swigCPtr, this, variable);
  }

  public String getCurrentFilename() {
    return CCMCJNI.CDFFileReader_getCurrentFilename(swigCPtr, this);
  }

}
