/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class GeneralFileReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GeneralFileReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeneralFileReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_GeneralFileReader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeneralFileReader() {
    this(CCMCJNI.new_GeneralFileReader(), true);
  }

  public int open(String filename) {
    return CCMCJNI.GeneralFileReader_open(swigCPtr, this, filename);
  }

  public vector_float getVariable(String variable) {
    long cPtr = CCMCJNI.GeneralFileReader_getVariable__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getVariable(int variableID) {
    long cPtr = CCMCJNI.GeneralFileReader_getVariable__SWIG_1(swigCPtr, this, variableID);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getVariable(String variable, int startIndex, int count) {
    long cPtr = CCMCJNI.GeneralFileReader_getVariable__SWIG_2(swigCPtr, this, variable, startIndex, count);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getVariable(int variableID, int startIndex, int count) {
    long cPtr = CCMCJNI.GeneralFileReader_getVariable__SWIG_3(swigCPtr, this, variableID, startIndex, count);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public float getVariableAtIndex(String variable, int index) {
    return CCMCJNI.GeneralFileReader_getVariableAtIndex__SWIG_0(swigCPtr, this, variable, index);
  }

  public float getVariableAtIndex(int variable_id, int index) {
    return CCMCJNI.GeneralFileReader_getVariableAtIndex__SWIG_1(swigCPtr, this, variable_id, index);
  }

  public vector_int getVariableInt(String variable) {
    long cPtr = CCMCJNI.GeneralFileReader_getVariableInt(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_int(cPtr, false);
  }

  public int getVariableIntAtIndex(String variable, int index) {
    return CCMCJNI.GeneralFileReader_getVariableIntAtIndex(swigCPtr, this, variable, index);
  }

  public int getNumberOfGlobalAttributes() {
    return CCMCJNI.GeneralFileReader_getNumberOfGlobalAttributes(swigCPtr, this);
  }

  public int getNumberOfVariables() {
    return CCMCJNI.GeneralFileReader_getNumberOfVariables(swigCPtr, this);
  }

  public int getNumberOfVariableAttributes() {
    return CCMCJNI.GeneralFileReader_getNumberOfVariableAttributes(swigCPtr, this);
  }

  public int getNumberOfRecords(String variable) {
    return CCMCJNI.GeneralFileReader_getNumberOfRecords__SWIG_0(swigCPtr, this, variable);
  }

  public int getNumberOfRecords(int variable_id) {
    return CCMCJNI.GeneralFileReader_getNumberOfRecords__SWIG_1(swigCPtr, this, variable_id);
  }

  public int getVariableID(String variable) {
    return CCMCJNI.GeneralFileReader_getVariableID(swigCPtr, this, variable);
  }

  public String getVariableName(int variable_id) {
    return CCMCJNI.GeneralFileReader_getVariableName(swigCPtr, this, variable_id);
  }

  public Attribute getGlobalAttribute(int i) {
    return new Attribute(CCMCJNI.GeneralFileReader_getGlobalAttribute__SWIG_0(swigCPtr, this, i), true);
  }

  public String getGlobalAttributeName(int attribute_id) {
    return CCMCJNI.GeneralFileReader_getGlobalAttributeName(swigCPtr, this, attribute_id);
  }

  public String getVariableAttributeName(int attribute_id) {
    return CCMCJNI.GeneralFileReader_getVariableAttributeName(swigCPtr, this, attribute_id);
  }

  public Attribute getGlobalAttribute(String attribute) {
    return new Attribute(CCMCJNI.GeneralFileReader_getGlobalAttribute__SWIG_1(swigCPtr, this, attribute), true);
  }

  public Attribute getVariableAttribute(String variable, String attribute) {
    return new Attribute(CCMCJNI.GeneralFileReader_getVariableAttribute(swigCPtr, this, variable, attribute), true);
  }

  public vector_string getVariableAttributeNames() {
    return new vector_string(CCMCJNI.GeneralFileReader_getVariableAttributeNames(swigCPtr, this), true);
  }

  public boolean doesAttributeExist(String attribute) {
    return CCMCJNI.GeneralFileReader_doesAttributeExist(swigCPtr, this, attribute);
  }

  public boolean doesVariableExist(String variable) {
    return CCMCJNI.GeneralFileReader_doesVariableExist(swigCPtr, this, variable);
  }

  public int close() {
    return CCMCJNI.GeneralFileReader_close(swigCPtr, this);
  }

  public String getCurrentFilename() {
    return CCMCJNI.GeneralFileReader_getCurrentFilename(swigCPtr, this);
  }

}
