/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class MAS extends Model {
  private long swigCPtr;

  protected MAS(long cPtr, boolean cMemoryOwn) {
    super(CCMCJNI.MAS_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MAS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_MAS(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MAS() {
    this(CCMCJNI.new_MAS(), true);
  }

  public int open(String filename) {
    return CCMCJNI.MAS_open(swigCPtr, this, filename);
  }

  public Interpolator createNewInterpolator() {
    long cPtr = CCMCJNI.MAS_createNewInterpolator(swigCPtr, this);
    return (cPtr == 0) ? null : new Interpolator(cPtr, false);
  }

  public vector_float getRPosGrid(String variable) {
    long cPtr = CCMCJNI.MAS_getRPosGrid__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getRPosGrid(int variable_id) {
    long cPtr = CCMCJNI.MAS_getRPosGrid__SWIG_1(swigCPtr, this, variable_id);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public String getRPosGridName(String variable) {
    return CCMCJNI.MAS_getRPosGridName__SWIG_0(swigCPtr, this, variable);
  }

  public String getRPosGridName(int variable) {
    return CCMCJNI.MAS_getRPosGridName__SWIG_1(swigCPtr, this, variable);
  }

  public vector_float getLatPosGrid(String variable) {
    long cPtr = CCMCJNI.MAS_getLatPosGrid__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getLatPosGrid(int variable_id) {
    long cPtr = CCMCJNI.MAS_getLatPosGrid__SWIG_1(swigCPtr, this, variable_id);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public String getLatPosGridName(String variable) {
    return CCMCJNI.MAS_getLatPosGridName__SWIG_0(swigCPtr, this, variable);
  }

  public String getLatPosGridName(int variable_id) {
    return CCMCJNI.MAS_getLatPosGridName__SWIG_1(swigCPtr, this, variable_id);
  }

  public vector_float getLonPosGrid(int variable_id) {
    long cPtr = CCMCJNI.MAS_getLonPosGrid(swigCPtr, this, variable_id);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_float getlonPosGrid(String variable) {
    long cPtr = CCMCJNI.MAS_getlonPosGrid(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public String getLonPosGridName(String variable) {
    return CCMCJNI.MAS_getLonPosGridName__SWIG_0(swigCPtr, this, variable);
  }

  public String getLonPosGridName(int variable_id) {
    return CCMCJNI.MAS_getLonPosGridName__SWIG_1(swigCPtr, this, variable_id);
  }

  public boolean getChangeSignFlag(String variable) {
    return CCMCJNI.MAS_getChangeSignFlag__SWIG_0(swigCPtr, this, variable);
  }

  public boolean getChangeSignFlag(int variable_id) {
    return CCMCJNI.MAS_getChangeSignFlag__SWIG_1(swigCPtr, this, variable_id);
  }

  public vector_string getLoadedVariables() {
    return new vector_string(CCMCJNI.MAS_getLoadedVariables(swigCPtr, this), true);
  }

}
