/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class Model extends GeneralFileReader {
  private long swigCPtr;

  protected Model(long cPtr, boolean cMemoryOwn) {
    super(CCMCJNI.Model_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Model obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_Model(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int open(String filename) {
    return CCMCJNI.Model_open(swigCPtr, this, filename);
  }

  public void setModelName(String modelName) {
    CCMCJNI.Model_setModelName(swigCPtr, this, modelName);
  }

  public String getModelName() {
    return CCMCJNI.Model_getModelName(swigCPtr, this);
  }

  public int loadVariable(String variable) {
    return CCMCJNI.Model_loadVariable(swigCPtr, this, variable);
  }

  public int unloadVariable(String variable) {
    return CCMCJNI.Model_unloadVariable(swigCPtr, this, variable);
  }

  public int loadVariableInt(String variable) {
    return CCMCJNI.Model_loadVariableInt(swigCPtr, this, variable);
  }

  public vector_float getVariableFromMapRW(String variable) {
    long cPtr = CCMCJNI.Model_getVariableFromMapRW__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_int getIntVariableFromMapRW(String variable) {
    long cPtr = CCMCJNI.Model_getIntVariableFromMapRW__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_int(cPtr, false);
  }

  public vector_float getVariableFromMap(String variable) {
    long cPtr = CCMCJNI.Model_getVariableFromMap__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_int getIntVariableFromMap(String variable) {
    long cPtr = CCMCJNI.Model_getIntVariableFromMap__SWIG_0(swigCPtr, this, variable);
    return (cPtr == 0) ? null : new vector_int(cPtr, false);
  }

  public vector_float getVariableFromMap(int variable_id) {
    long cPtr = CCMCJNI.Model_getVariableFromMap__SWIG_1(swigCPtr, this, variable_id);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_int getIntVariableFromMap(int variable_id) {
    long cPtr = CCMCJNI.Model_getIntVariableFromMap__SWIG_1(swigCPtr, this, variable_id);
    return (cPtr == 0) ? null : new vector_int(cPtr, false);
  }

  public vector_float getVariableFromMapRW(int variable_id) {
    long cPtr = CCMCJNI.Model_getVariableFromMapRW__SWIG_1(swigCPtr, this, variable_id);
    return (cPtr == 0) ? null : new vector_float(cPtr, false);
  }

  public vector_int getIntVariableFromMapRW(int variable_id) {
    long cPtr = CCMCJNI.Model_getIntVariableFromMapRW__SWIG_1(swigCPtr, this, variable_id);
    return (cPtr == 0) ? null : new vector_int(cPtr, false);
  }

  public vector_string getLoadedVariables() {
    return new vector_string(CCMCJNI.Model_getLoadedVariables(swigCPtr, this), true);
  }

  public void setMissingValue(float missingValue) {
    CCMCJNI.Model_setMissingValue(swigCPtr, this, missingValue);
  }

  public float getMissingValue() {
    return CCMCJNI.Model_getMissingValue(swigCPtr, this);
  }

  public float getConversionFactorToSI(String variable) {
    return CCMCJNI.Model_getConversionFactorToSI(swigCPtr, this, variable);
  }

  public String getNativeUnit(String variable) {
    return CCMCJNI.Model_getNativeUnit(swigCPtr, this, variable);
  }

  public String getSIUnit(String variable) {
    return CCMCJNI.Model_getSIUnit(swigCPtr, this, variable);
  }

  public int getProgress() {
    return CCMCJNI.Model_getProgress(swigCPtr, this);
  }

  public int getBusyStatus() {
    return CCMCJNI.Model_getBusyStatus(swigCPtr, this);
  }

  public int close() {
    return CCMCJNI.Model_close(swigCPtr, this);
  }

  public Interpolator createNewInterpolator() {
    long cPtr = CCMCJNI.Model_createNewInterpolator(swigCPtr, this);
    return (cPtr == 0) ? null : new Interpolator(cPtr, false);
  }

  public final static int BUSY = CCMCJNI.Model_BUSY_get();
  public final static int OK = CCMCJNI.Model_OK_get();
}
