/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class Point3f {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Point3f(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point3f obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_Point3f(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point3f(float component1, float component2, float component3) {
    this(CCMCJNI.new_Point3f__SWIG_0(component1, component2, component3), true);
  }

  public Point3f(float component1, float component2, float component3, Point3f.Coordinates c) {
    this(CCMCJNI.new_Point3f__SWIG_1(component1, component2, component3, c.swigValue()), true);
  }

  public Point3f(Point3f p) {
    this(CCMCJNI.new_Point3f__SWIG_2(Point3f.getCPtr(p), p), true);
  }

  public Point3f() {
    this(CCMCJNI.new_Point3f__SWIG_3(), true);
  }

  public Point3f(Point3f.Coordinates c) {
    this(CCMCJNI.new_Point3f__SWIG_4(c.swigValue()), true);
  }

  public void normalize() {
    CCMCJNI.Point3f_normalize(swigCPtr, this);
  }

  public String toString() {
    return CCMCJNI.Point3f_toString(swigCPtr, this);
  }

  public float magnitude() {
    return CCMCJNI.Point3f_magnitude(swigCPtr, this);
  }

  public float distance(Point3f p) {
    return CCMCJNI.Point3f_distance(swigCPtr, this, Point3f.getCPtr(p), p);
  }

  public void setComponent1(float value) {
    CCMCJNI.Point3f_component1_set(swigCPtr, this, value);
  }

  public float getComponent1() {
    return CCMCJNI.Point3f_component1_get(swigCPtr, this);
  }

  public void setComponent2(float value) {
    CCMCJNI.Point3f_component2_set(swigCPtr, this, value);
  }

  public float getComponent2() {
    return CCMCJNI.Point3f_component2_get(swigCPtr, this);
  }

  public void setComponent3(float value) {
    CCMCJNI.Point3f_component3_set(swigCPtr, this, value);
  }

  public float getComponent3() {
    return CCMCJNI.Point3f_component3_get(swigCPtr, this);
  }

  public void setCoordinates(Point3f.Coordinates c) {
    CCMCJNI.Point3f_setCoordinates(swigCPtr, this, c.swigValue());
  }

  public Point3f.Coordinates getCoordinates() {
    return Point3f.Coordinates.swigToEnum(CCMCJNI.Point3f_getCoordinates(swigCPtr, this));
  }

  public Point3f getCartesian() {
    return new Point3f(CCMCJNI.Point3f_getCartesian(swigCPtr, this), true);
  }

  public final static class Coordinates {
    public final static Point3f.Coordinates SPHERICAL = new Point3f.Coordinates("SPHERICAL");
    public final static Point3f.Coordinates CARTESIAN = new Point3f.Coordinates("CARTESIAN");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Coordinates swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Coordinates.class + " with value " + swigValue);
    }

    private Coordinates(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Coordinates(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Coordinates(String swigName, Coordinates swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Coordinates[] swigValues = { SPHERICAL, CARTESIAN };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
