/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class SWIGTYPE_p_boost__unordered_mapT_int_ccmc__GeneralFileReader_p_t {
  private long swigCPtr;

  protected SWIGTYPE_p_boost__unordered_mapT_int_ccmc__GeneralFileReader_p_t(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_boost__unordered_mapT_int_ccmc__GeneralFileReader_p_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_boost__unordered_mapT_int_ccmc__GeneralFileReader_p_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

