/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gov.nasa.gsfc.ccmc;

public class Time {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Time(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Time obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCMCJNI.delete_Time(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setYear(int value) {
    CCMCJNI.Time_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return CCMCJNI.Time_year_get(swigCPtr, this);
  }

  public void setMonth(int value) {
    CCMCJNI.Time_month_set(swigCPtr, this, value);
  }

  public int getMonth() {
    return CCMCJNI.Time_month_get(swigCPtr, this);
  }

  public void setDay(int value) {
    CCMCJNI.Time_day_set(swigCPtr, this, value);
  }

  public int getDay() {
    return CCMCJNI.Time_day_get(swigCPtr, this);
  }

  public void setHour(int value) {
    CCMCJNI.Time_hour_set(swigCPtr, this, value);
  }

  public int getHour() {
    return CCMCJNI.Time_hour_get(swigCPtr, this);
  }

  public void setMinute(int value) {
    CCMCJNI.Time_minute_set(swigCPtr, this, value);
  }

  public int getMinute() {
    return CCMCJNI.Time_minute_get(swigCPtr, this);
  }

  public void setSecond(float value) {
    CCMCJNI.Time_second_set(swigCPtr, this, value);
  }

  public float getSecond() {
    return CCMCJNI.Time_second_get(swigCPtr, this);
  }

  public Time() {
    this(CCMCJNI.new_Time(), true);
  }

}
